#!/bin/sh

NETS="superhero2 xbl"

for NET in ${NETS}; do
    tmux has-session -t ${NET} 2>/dev/null
    if [ $? != 0 ]; then
        tmux new-session -s ${NET} -d
        tmux send-keys -t ${NET} "eosconf_${NET} && eos_walletd" C-m
        tmux split-window -h
        tmux send-keys -t ${NET} "eosconf_${NET} && eosd -s" C-m
        tmux select-pane -L
        tmux split-window -v
        tmux send-keys -t ${NET} "eosconf_${NET}" C-m
        tmux resize-pane -U 20
        tmux resize-pane -R 15
    fi
done

tmux attach -t ${NET}
